default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_URL"] || "ezpoisk_prod" %>

  # 1(web_concurrency) * 5(threads) + 13(sidekiq concurrency) + 1(rails console) <= 20 (connections limit on heroku)
  pool: <%= ENV["MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: ezpoisk_development

test:
  <<: *default
  database: ezpoisk_test

production:
  <<: *default
