default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_URL"] || "ezpoisk_prod" %>
  pool: 5

development:
  <<: *default
  database: ezpoisk_development

test:
  <<: *default
  database: ezpoisk_test

production:
  <<: *default
