default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ezpoisk_development

test:
  <<: *default
  database: ezpoisk_test

production:
  <<: *default
