default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chogde_development

test:
  <<: *default
  database: chogde_test

production:
  <<: *default
